### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by msolution79** [Rob117/react-native-dynamic-cropper#5]
Hi Rob117, 

How are you? I'd like to use this dynamic-cropper in my project. May I know when android version will come? 

Thanks.

**Comment by Rob117** [comment]
Hey!
So, right now I'm building out a very, very complicated backend for an app that I will use this in. Do you have kotlin/java experience? I can point you to the library that this will bridge if you have the experience

**Comment by Rob117** [comment]
Just a heads-up to the world - I'm still cracking away at the server side of the project, I promise I haven't forgotten about you guys
