### ISSUE TITLE
Dynamic image name

### ISSUE THREAD

**Issue by shalin-jasani** [Rob117/react-native-dynamic-cropper#6]
Hi @Rob117 is there any way to pass image name for the new cropped image instead of static "temp.jpg" name? I have tried but I'm not able to get image name. Can you please help me here?

**Comment by Rob117** [comment]
Yeah, I can help you this weekend - I'm really swamped with this deploy thing, but that should be a really fast edit in the code. I'll try to get to it saturday morning Japan time, but no promises

**Comment by shalin-jasani** [comment]
No worries and thanks in advance

**Comment by Rob117** [comment]
@shalin-jasani 
Done! I also cleaned the readme up and updated the podfile explanation, so using it should be more straightforward.

If this doesn't solve your problem, please reopen the issue. Thank you!

**Comment by SinanBaymammadli** [comment]
Hi @Rob117, thanks for the component, I think you forgot to publish this change to npm. Latest version (0.1.0) doesn't have `filePath` option. Can you publish it?

**Comment by shalin-jasani** [comment]
> @shalin-jasani
> Done! I also cleaned the readme up and updated the podfile explanation, so using it should be more straightforward.
> 
> If this doesn't solve your problem, please reopen the issue. Thank you!

Thanks @Rob117 for such a quick change

**Comment by Rob117** [comment]
@SinanBaymammadli I DID forget to publish it! I feel pretty silly - I'll get that done tonight (JST)
