### ISSUE TITLE
Feature Request: Crop 2 images(background-image and image) into a single output image.

### ISSUE THREAD

**Issue by svenkatesh-nyros** [Rob117/react-native-dynamic-cropper#8]
Is it possible to provide the source image in a existing background image to crop them into single image using this package.
following is the example working urls for making this feature.

http://subinsb.com/create-profile-picture-framer-web-app/

Git url: https://github.com/subins2000/profile-picture-framer

can this feature implemented in your package ?

**Comment by Rob117** [comment]
So, right now as a stopgap measure, this library is a react-native wrapper for a library that a much more skilled developer has released.

If you want feature requests, make sure they exists/open a feature request [here](https://github.com/TimOliver/TOCropViewController), then if they implement/have it, let me know. If they do have it, please reopen the comment! :)
